### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by marvdias** [facebookincubator/CommunityCellularManager#84]
Connection refused while trying to adjust credit or send sms to user. And when I go back to the subscriber page's i can see that the request is not completed, its in the pending list.

The web cloud shows: 
```
Internal Server Error: /dashboard/subscribers/IMSI724119111341404/send-sms
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/cloud/endagaweb/views/dashboard.py", line 53, in dispatch
    return super(ProtectedView, self).dispatch(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vagrant/cloud/endagaweb/views/dashboard.py", line 490, in post
    tasks.async_post.delay(url, params)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
[27/Oct/2017 19:03:42] ERROR [exception.py:124] Internal Server Error: /dashboard/subscribers/IMSI724119111341404/send-sms
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/cloud/endagaweb/views/dashboard.py", line 53, in dispatch
    return super(ProtectedView, self).dispatch(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vagrant/cloud/endagaweb/views/dashboard.py", line 490, in post
    tasks.async_post.delay(url, params)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/vagrant/.virtualenvs/endaga/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
```

**Comment by marvdias** [comment]
I added some credit to my users directly in the db cloud ($700,000.00) for each one. Than I could send sms between them, but I don't know why, there is a initial cost of $1,515.47. However I still cannot make calls, it does not even complete the dialing! Any ideas?

**Comment by kheimerl** [comment]
This is expected behavior in the VMs. The VM setup doesn't turn on rabbitMQ
which is the handler for these two commands. Credit can be added manually
on the BTS through a script (something like "credit_cli").

**Comment by marvdias** [comment]
Thanks @kheimerl ! And regarding the calls?

**Comment by kheimerl** [comment]
You'll need to check into the FS instance on the client VM to look for the
error.
